
CREATE USER IF NOT EXISTS 'marcello' IDENTIFIED BY '1234';

GRANT ALL ON `SimaplaDb`.* TO 'marcello';
GRANT SELECT ON TABLE `SimaplaDb`.* TO 'marcello';
GRANT SELECT, INSERT, TRIGGER ON TABLE `SimaplaDb`.* TO 'marcello';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `SimaplaDb`.* TO 'marcello';
GRANT EXECUTE ON `SimaplaDb`.* TO 'marcello';
CREATE USER IF NOT EXISTS 'fabian' IDENTIFIED BY '1234';

GRANT SELECT ON TABLE `SimaplaDb`.* TO 'fabian';
GRANT SELECT, INSERT, TRIGGER ON TABLE `SimaplaDb`.* TO 'fabian';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `SimaplaDb`.* TO 'fabian';
GRANT EXECUTE ON `SimaplaDb`.* TO 'fabian';
CREATE USER IF NOT EXISTS 'emilio' IDENTIFIED BY '1234';

GRANT SELECT ON TABLE `SimaplaDb`.* TO 'emilio';
GRANT SELECT, INSERT, TRIGGER ON TABLE `SimaplaDb`.* TO 'emilio';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `SimaplaDb`.* TO 'emilio';
GRANT EXECUTE ON `SimaplaDb`.* TO 'emilio';
CREATE USER IF NOT EXISTS 'nicolas' IDENTIFIED BY '1234';

GRANT SELECT, INSERT, TRIGGER ON TABLE `SimaplaDb`.* TO 'WebClient';
GRANT EXECUTE ON `SimaplaDb`.* TO 'WebClient';
GRANT SELECT ON TABLE `SimaplaDb`.* TO 'WebClient';
CREATE USER IF NOT EXISTS 'WebService' IDENTIFIED BY 'ws*3';

GRANT SELECT ON TABLE `SimaplaDb`.* TO 'WebService';
GRANT SELECT, INSERT, TRIGGER ON TABLE `SimaplaDb`.* TO 'WebService';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `SimaplaDb`.* TO 'WebService';
GRANT EXECUTE ON `SimaplaDb`.* TO 'WebService';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
